### ISSUE TITLE
no options to customise the indicators

### ISSUE THREAD

**Issue by neemanwa** [kolking/react-native-page-indicator#5]
<img width="211" alt="Screenshot 2023-06-23 at 7 46 26 PM" src="https://github.com/kolking/react-native-page-indicator/assets/103624938/fb619878-7a75-4aeb-91fd-d68f4c9b6c09">

Want to achieve something like this..!
border color, fill color for inactive indicator, active indicators etc.

**Comment by kolking** [comment]
The component does not allow passing an arbitrary style for indicators, therefore the borders won't work. But if you agree to use a solid background instead of a border for inactive indicators, you can get the following look:

<img width="160" alt="Снимок экрана 2023-06-23 в 22 44 47" src="https://github.com/kolking/react-native-page-indicator/assets/4656448/568a0ba4-9863-4c45-89c9-1fed9f72a2f5">

**Comment by neemanwa** [comment]
No solid background won't work for me
